# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbf/user/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbf.user import base_pb2 as tbf_dot_user_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbf/user/user.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007go/user',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13tbf/user/user.proto\x1a\x13tbf/user/base.proto\"\x1c\n\x0eGetByIDRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x32\n\x0bUserService\x12#\n\x07GetByID\x12\x0f.GetByIDRequest\x1a\x05.User\"\x00\x42\tZ\x07go/userb\x06proto3'
  ,
  dependencies=[tbf_dot_user_dot_base__pb2.DESCRIPTOR,])




_GETBYIDREQUEST = _descriptor.Descriptor(
  name='GetByIDRequest',
  full_name='GetByIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetByIDRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['GetByIDRequest'] = _GETBYIDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetByIDRequest = _reflection.GeneratedProtocolMessageType('GetByIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBYIDREQUEST,
  '__module__' : 'tbf.user.user_pb2'
  # @@protoc_insertion_point(class_scope:GetByIDRequest)
  })
_sym_db.RegisterMessage(GetByIDRequest)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=124,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetByID',
    full_name='UserService.GetByID',
    index=0,
    containing_service=None,
    input_type=_GETBYIDREQUEST,
    output_type=tbf_dot_user_dot_base__pb2._USER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
