# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tbf/user/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tbf.user import base_pb2 as tbf_dot_user_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tbf/user/user.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007go/user',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13tbf/user/user.proto\x1a\x13tbf/user/base.proto\"\x1c\n\x0eGetByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"&\n\x0fGetByIdResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User2=\n\x0bUserService\x12.\n\x07GetById\x12\x0f.GetByIdRequest\x1a\x10.GetByIdResponse\"\x00\x42\tZ\x07go/userb\x06proto3'
  ,
  dependencies=[tbf_dot_user_dot_base__pb2.DESCRIPTOR,])




_GETBYIDREQUEST = _descriptor.Descriptor(
  name='GetByIdRequest',
  full_name='GetByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetByIdRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=72,
)


_GETBYIDRESPONSE = _descriptor.Descriptor(
  name='GetByIdResponse',
  full_name='GetByIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='GetByIdResponse.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=112,
)

_GETBYIDRESPONSE.fields_by_name['user'].message_type = tbf_dot_user_dot_base__pb2._USER
DESCRIPTOR.message_types_by_name['GetByIdRequest'] = _GETBYIDREQUEST
DESCRIPTOR.message_types_by_name['GetByIdResponse'] = _GETBYIDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetByIdRequest = _reflection.GeneratedProtocolMessageType('GetByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBYIDREQUEST,
  '__module__' : 'tbf.user.user_pb2'
  # @@protoc_insertion_point(class_scope:GetByIdRequest)
  })
_sym_db.RegisterMessage(GetByIdRequest)

GetByIdResponse = _reflection.GeneratedProtocolMessageType('GetByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBYIDRESPONSE,
  '__module__' : 'tbf.user.user_pb2'
  # @@protoc_insertion_point(class_scope:GetByIdResponse)
  })
_sym_db.RegisterMessage(GetByIdResponse)


DESCRIPTOR._options = None

_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=114,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetById',
    full_name='UserService.GetById',
    index=0,
    containing_service=None,
    input_type=_GETBYIDREQUEST,
    output_type=_GETBYIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
